# Generated by Django 4.2.2 on 2023-06-26 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="resturants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_id", models.BigIntegerField()),
                ("hotel_name", models.CharField(max_length=200)),
                ("hotel_location", models.CharField(max_length=200)),
                ("hotel_langitude", models.CharField(max_length=200)),
                ("hotel_longitude", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="menus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food", models.CharField(max_length=200)),
                ("price", models.CharField(max_length=100)),
                (
                    "hotel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodweb.resturants",
                    ),
                ),
            ],
        ),
    ]
